- name: Set up a dev environment
  hosts: all
  vars_prompt:
    - name: email
      prompt: email account for git
    - name: fullname
      prompt: your full name
  vars:
    - neovim_version: v0.10.3
    - fzf_version: v0.58.0
    - tmux_version: 3.5a
  roles:
    - packages
    - nvim
    - tmux
    - fzf
    - marks
    - nvm
    - dotfiles
    - git
