- name: Set up a dev environment
  hosts: all
    vars_prompt:
    - name: email
      prompt: email account for git
    - name: fullname
      prompt: your full name
  roles:
    - packages
    - nvim
    - tmux
    - fzf
    - marks
    - nvm
    - dotfiles
    - git
