- name: Set up a dev environment
  hosts: all
  vars_prompt:
    - name: email
      prompt: email account for git
  roles:
    - packages
    - nvim
    - tmux
    - fzf
    - marks
    - nvm
    - dotfiles
