---
- hosts: all
  tasks:
    - name: Create git directory in home directory
      file: "path={{ ansible_env.HOME }}/git state=directory"
    - name: Clone dotfiles repo
      git: 
        repo: https://github.com/pbellens/dotfiles
        dest: "{{ ansible_env.HOME }}/git/dotfiles"
            - name: Clone dotfiles repo
    -name: Update font cache  
     ansible.builtin.command: 
        cmd: fc-cache -rv
