---
- hosts: all
  tasks:
    - name: Create bin in home directory
      file: "path={{ ansible_env.HOME }}/.local/bin state=directory"
    - name: Download nvim appimage
      get_url: 
        url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage 
        dest: "{{ ansible_env.HOME }}/.local/bin"
        mode: 0755
    - name: Symlink as nvim
      ansible.builtin.file:
        src: "{{ ansible_env.HOME }}/.local/bin/nvim.appimage"
        dest: "{{ ansible_env.HOME }}/.local/bin/nvim"
        state: link
    - name: Add alias for vim
      lineinfile:
        path="{{ ansible_env.HOME }}/.bashrc"
        line="alias vim=nvim"
        regexp='^alias vim='
        state=present
        insertafter=EOF
