---
- hosts: all
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name:
          - git
          - stow
          - xclip
        state: present
      become: yes
