---
- name: Create bin in home directory
  file: "path={{ ansible_env.HOME }}/.local/bin state=directory"

- name: Clone main of neovim repository
  git:
    repo: https://github.com/neovim/neovim
    dest: "{{ ansible_env.HOME }}/git/neovim"
    clone: yes
    update: yes
    depth: 1

- name: Build the source
  ansible.builtin.shell: |
    rm -fr build
    cd $HOME/git/neovim
    make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$HOME/neovim"
    make install

- name: Symlink as nvim
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/neovim/bin/nvim"
    dest: "{{ ansible_env.HOME }}/.local/bin/nvim"
    state: link

- name: Add alias for vim
  lineinfile:
    path="{{ ansible_env.HOME }}/.bashrc"
    line="alias vim=nvim"
    regexp='^alias vim='
    state=present
    insertafter=EOF
